### ISSUE TITLE
Registry Can't Contact docker-auth Service

### ISSUE THREAD

**Issue by afrazkhan** [kwk/docker_auth#2]
The docker-auth service seems to be running okay, or at least it answers as expected on localhost:5001. However, no matter what I try in my registry config, I get: `getsockopt: connection refused`.

For example: `REGISTRY_AUTH_TOKEN_REALM='https://0.0.0.0:5001/auth` yields `dial tcp [MY IP]:443: getsockopt: connection refused`.

I've also tried:
* `REGISTRY_AUTH_TOKEN_REALM='https://127.0.0.1:5001/auth'`
* `REGISTRY_AUTH_TOKEN_REALM='https://[INTERNAL_DNS_NAME]:5001/auth'`
* `REGISTRY_AUTH_TOKEN_REALM='https://[EXTERNAL_DNS_NAME]:5001/auth'`

and many more that I've forgotten now. Anything I put in there, comes back immediately as unable to connect.

## Full Configuration for docker-auth:
```
server:
  addr: ":5001"
  certificate: "[PATH TO CERT]"
  key: "[PATH TO KEY]"
token:
  issuer: "[ME :)]"
  expiration: 900
ldap_auth:
  addr: "[LDAP ADDRESS]:389"
  tls: "always"
  insecure_tls_skip_verify: true
  bind_dn: "[BIND DN]"
  bind_password_file: /root/.ldap-password
  # User query settings. ${account} is expanded from auth request 
  base: "[BASE]"
  filter: "uid=${account}"
acl:
  - match:
      account: /.+/
    actions: ['*']
```

## Full Configuration for Registry
```
docker run \
  --name=docker \
  -d \
  -e DEBUG=True \
  -e LOGLEVEL=debug \
  -e REGISTRY_STORAGE_S3_BUCKET="[BUCKET NAME]" \
  -e REGISTRY_STORAGE=s3 \
  -e SETTINGS_FLAVOR=s3 \
  -e REGISTRY_STORAGE_S3_REGION="eu-west-1" \
  -e REGISTRY_STORAGE_S3_ROOTDIRECTORY="/" \
  -e SEARCH_BACKEND=sqlalchemy \
  -e REGISTRY_HTTP_TLS_CERTIFICATE="[CERT]" \
  -e REGISTRY_HTTP_TLS_KEY="[KEY]" \
  -e REGISTRY_AUTH=token \
  -e REGISTRY_AUTH_TOKEN_REALM='https://0.0.0.0:5001/auth' \
  -e REGISTRY_AUTH_TOKEN_SERVICE='[ME :)]' \
  -e REGISTRY_AUTH_TOKEN_ISSUER='[ISSUER]' \
  -e REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE='/root/cert_bundle.pem' \
  -v [SSL DIR]/:[SSL DIR] \
  -v [PATH TO BUNDLE]:/root/cert_bundle.pem \
  -p 443:5000 \
  library/registry
```

I noticed you have a complete example written up with Docker Compose [here](https://github.com/kwk/docker-registry-setup/). Following that line by line, I get the exact same error.
